### ISSUE TITLE
Choose Project Management Technique

### ISSUE THREAD

**Issue by kmn6** [jidone7061/mywebclass-simulation#1]
On sprint_1_project_management.md we are instructed to choose between Kanban, Scrum, or Scrumban.

**Comment by kmn6** [comment]
I think we should select Scrumban. Scrum has rigid roles such as Product Owner, Scrum Master, and Development Team but it doesn't make sense for us to have these roles with just the two of us. In my opinion, Kanban is more suitable for us as IT professionals because it fits in with the roles of limiting work in process and identifying bottlenecks in work. In the end, we will end up with a hybrid Scrumban any way as we have to implement parts of Scrum such as doing work in sprints and having a retrospective. We might as well just call it out and make a formal declaration.

**Comment by jidone7061** [comment]
Good morning Kevin,  I will review Scrumban since I am not too familiar with it.  I am fine with your judgement call and calling it out.  I believe it is flexible and expected to adjust items where we feel necessary as we move along so we could always change it if we feel it is not effective in this project.
