### ISSUE TITLE
As a user, I would like to consistently view the same navigation bar on all pages so that I can browse the website without getting lost.

### ISSUE THREAD

**Issue by kmn6** [jidone7061/mywebclass-simulation#36]
Theme: Responsive Content Template and Homepage
Initiative: Website Redesign and Optimization
Epic: Develop Responsive Content Template

Acceptance Criteria:
- playwright test that checks for every link in the header and that the wording is correct
- playwright test that follows the links

**Comment by jidone7061** [comment]
I noticed that the title of the privacy page is actually "MyWebclass.org | Our Story"   That is why the Google analytics shows this page several times instead of when you click on the privacy notice it reflecting the name of the HTML file.  Google analytics reports on what the title of the page is, not the filename.

**Comment by kmn6** [comment]
For the title name consistency, maybe we should make that into a separate user story. This one is for the nav bar
